### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by tingkai-zhang** [rixwew/pytorch-fm#6]
Hi, I googled this error but didn't help solve this error. 

```
Traceback (most recent call last):
  File "/root/pytorchfm/examples/main.py", line 157, in <module>
    args.save_dir)
  File "/root/pytorchfm/examples/main.py", line 127, in main
    train(model, optimizer, train_data_loader, criterion, device)
  File "/root/pytorchfm/examples/main.py", line 81, in train
    y = model(fields)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/pytorchfm/torchfm/model/xdfm.py", line 27, in forward
    x = self.linear(x) + self.cin(embed_x) + self.mlp(embed_x.view(-1, self.embed_output_dim))
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/pytorchfm/torchfm/layer.py", line 232, in forward
    x = F.relu(self.conv_layers[i](x))
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 943, in relu
    result = torch.relu(input)
RuntimeError: CUDA error: device-side assert triggered
```

Can you take a look at it? Thank you!

**Comment by Drone-Banks** [comment]
If you use the MovieLens dataset, the ID begins from 1, so you should change all the embedding codes
```python
# origin:
torch.nn.Embedding(sum(field_dims), ....)
# now:
torch.nn.Embedding(sum(field_dims)+1, ...)
```

**Comment by tingkai-zhang** [comment]
> If you use the MovieLens dataset, the ID begins from 1, so you should change all the embedding codes
> 
> ```python
> # origin:
> torch.nn.Embedding(sum(field_dims), ....)
> # now:
> torch.nn.Embedding(sum(field_dims)+1, ...)
> ```

Resolved.
Thank you SO MUCH!
